theme: jekyll-theme-hacker
logo: https://avatars0.githubusercontent.com/u/72337471
title: reactive-stack-js-mysql-poc
description: reactive-stack-js mysql poc
show_downloads: "false"
include:
  - "_*_.html"
  - "_*_.*.html"
plugins:
  - jemoji